#ifndef __DEFS_H__
#define __DEFS_H__

#define SCREEN_WIDTH    1920
#define SCREEN_HEIGHT   1080

#define __DEBUG__

#define FPS     60

#define UI_MENU_TOP     976
#define UI_MENU_LEFT    0
#define UI_MENU_WIDTH   (SCREEN_WIDTH)
#define UI_MENU_HEIGHT  104

#define UI_BUTTON_SIZE  32

enum Button_t {
    BUTTON_CROSS, BUTTON_CIRCLE, BUTTON_SQUARE, BUTTON_TRIANGLE,
    BUTTON_R1, BUTTON_R2, BUTTON_L1, BUTTON_L2,
    BUTTON_START, BUTTON_SELECT
};

enum ButtonPosition_t {
    BUTTONPOSITION_LEFT,
    BUTTONPOSITION_MIDDLE,
    BUTTONPOSITION_RIGHT
};

#endif  // __DEFS_H__